#task 2
# Dockerfile для Service A
FROM python:3.10-slim

WORKDIR /usr/src/app

# Копіюємо файл залежностей та встановлюємо їх
COPY service_a/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Копіюємо код застосунку
COPY service_a/app.py .

EXPOSE 5000

CMD ["python", "app.py"]